In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
b=np.array(['hyd'])

In [ ]:
b

array(['hyd'], dtype='<U3')

In [ ]:
a.dtype

dtype('int64')

In [ ]:
np.random.random(20)

array([0.59421593, 0.41642697, 0.0262723 , 0.29781169, 0.01614187,
       0.12939311, 0.83981986, 0.89767759, 0.71076399, 0.04250396,
       0.55260474, 0.26265118, 0.30913783, 0.08862681, 0.07024431,
       0.36662424, 0.20335526, 0.47745205, 0.01788773, 0.48675904])

In [ ]:
np.floor(np.random.random())

0.0

In [ ]:
np.ceil(np.random.random())

1.0

In [ ]:
np.sqrt(100)

10.0

In [ ]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
c=np.arange(30).reshape(3,10,1)
c
c#to convert into proper matrix we use reshape and use the multiple of given number

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]]])

In [ ]:
#vertical stacking we use vstack  vstack((c,d)) and horizontal stacking we use hstack

In [ ]:
S=np.arange(100,200,5)
s=S*np.pi/180
a=pd.DataFrame(s,index=S,columns=['randiants'])
a.index=S
a.columns=['radians']


In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
s=np.arange(1,10)
s
np.random.seed(100)

In [ ]:
S=pd.DataFrame(np.random.randint(1,100,10),columns=['val'])
S

val
0   54
1   67
2   99
3   15
4   35
5   25
6   16
7   61
8   59
9   17

In [ ]:
plt.pie(S.val,labels=['s','a','d','f','g','h','k','l','o','y'])
plt.show()